#!/bin/bash

# this shit displays a notify dialog. set the time by $ crontab -e, not root!

kill -9 `pidof zenity`	# kill zenity for safety from a sin

temP=zz_note_bebe_temp	# i can't find a method to avoid a creation of a temp file!
note=note_bene		# 'note_bene' is a file with todo-list


cp $note $temP

DISPLAY=:0 zenity --text-info --editable --filename $temP > $note

if [[ -z `grep -i [а-яa-z] $note` ]]	# a protection on deleting of todo-list by 'esc'
  then cat $temP > $note
fi


rm $temP


