#! /bin/bash
# displays note from 'note_bene' via i3-nagbar
# removes it after 3 sec



# i don't know exactly about other notifiers, it kills them (blocked)
# just, notify-osd prevents to run dunst, so, i kill gnome-notifiers
#kill -SIGTERM `pidof notify-osd`
#kill -SIGTERM `pidof zenity`



# the option '-b' - button - is studied by me very slow, it is not correct now

aa=`cat ~/note_bene`
i3-nagbar -t warning -f pango:monospace 16 -m "	$aa" -b '' 'i3-msg exit' &
sleep 3
kill -9 `pidof i3-nagbar`
    
